name: flutter_compile
description: A Dart CLI to simplify the setting up your framework development environment, which describes and automates the steps you need to configure your computer to work on Flutter&#x27;s Framework
version: 0.0.1
publish_to: none

environment:
  sdk: ^3.4.0

dependencies:
  args: ^2.5.0
  cli_completion: ^0.5.0
  mason_logger: ^0.3.1
  pub_updater: ^0.4.0

dev_dependencies:
  build_runner: ^2.4.11
  build_verify: ^3.1.0
  build_version: ^2.1.1
  mocktail: ^1.0.4
  test: ^1.25.8
  very_good_analysis: ^6.0.0

executables:
  flutter_compile:
